# Generated by Django 3.2 on 2021-04-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodada',
            name='data_rodada',
            field=models.DateField(),
        ),
    ]
